# Generated by Django 5.2.4 on 2025-08-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('speciality', models.CharField(max_length=100)),
                ('maritalstatus', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('appointmenttime', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
