# Generated by Django 5.2.4 on 2025-08-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardname', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('staff', models.IntegerField()),
                ('visitinghours', models.TimeField()),
                ('rules', models.TextField()),
            ],
        ),
    ]
